# Generated by Django 4.1.6 on 2023-02-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMeDatabase',
        ),
    ]
