# Generated by Django 4.1.6 on 2023-02-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about_me', '0005_delete_aboutmedatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('second_name', models.CharField(max_length=15)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
